### ISSUE TITLE
Question about your CUDA render part

### ISSUE THREAD

**Issue by Guptajakala** [meiqua/pose_refine#1]
Dear author, this repo is really cool! I have a question about your CUDA render part.
I saw the function "render_triangle" seems to render tri-mesh. So:
1) Is the output Z-buffer of the rendered image?
2) In readme, you mentioned it can run "render handreds poes of a ply model at once". Is it possible to extend the code to render multiple object in each scene, and render all scenes at same time? 
Thank you for such amazing work!

**Comment by meiqua** [comment]
1. Yes, Z-buffer only.
2. Yes, but unlike same object in different poses, different objects may have different num of triangles. So you may need some skills like cuda stream to render them at once.
