### ISSUE TITLE
about cuda_build_kdtree 

### ISSUE THREAD

**Issue by joy-yjl** [meiqua/pose_refine#10]
Hi:
I follow the branch cuda_build_kdtree .I find there is a bug at pcd_scene.cu line 171 `num_nodes_now_host = num_nodes_now_dev;` 

 I change it to 'thrust::copy(num_nodes_now_dev.begin(), num_nodes_now_dev.end(), num_nodes_now_host.begin());' . But it have a bug, too.

Did you test this code?

**Comment by joy-yjl** [comment]
I think you can not copy host to device like this:

  //root
    nodes_dev.resize(1);
    Node_kdtree root_host;
    root_host.left = 0;
    root_host.right = pcd_buffer.size();
    nodes_dev[0] = root_host;

nodes_dev in device but root_host in host

**Comment by meiqua** [comment]
I can't remember if the codes are fully tested. I will have a look recently. For nodes_dev = root_host, it is a special thrust syntax, referring to [thrust wiki](https://github.com/thrust/thrust/wiki/Quick-Start-Guide) .  
Well, after reading codes for a while, I find that at that time I thought it's not necessary to build kdtree on cuda if calculating normals on cpu, so it was not tested then...

**Comment by meiqua** [comment]
Interesting, after some debug, I find the error is simply because we should re-assign pointer after resizing the thrust vector. Adding [this line](https://github.com/meiqua/pose_refine/blob/7a71e19dc48473b0164c3530174ce491ac56c73b/cuda_icp/scene/pcd_scene/pcd_scene.cu#L166) should be OK.

**Comment by joy-yjl** [comment]
> Interesting, after some debug, I find the error is simply because we should re-assign pointer after resizing the thrust vector. Adding [this line](https://github.com/meiqua/pose_refine/blob/7a71e19dc48473b0164c3530174ce491ac56c73b/cuda_icp/scene/pcd_scene/pcd_scene.cu#L166) should be OK.

Thanks for that. I will continue to learn
