### ISSUE TITLE
cuda_render test fail when each pose is different?

### ISSUE THREAD

**Issue by Guptajakala** [meiqua/pose_refine#2]
When I change the code [here](https://github.com/meiqua/pose_refine/blob/81b64d1910ee87c703fd3eabcda5362717fc4412/cuda_renderer/test.cpp#L61)

```
std::vector<cuda_renderer::Model::mat4x4> mat4_v(100, mat4);
for (auto &mat:mat4_v)
 {
        mat.c3 += static_cast <float> (rand()) / static_cast <float> (RAND_MAX) * 100;
 }
```

Then the result of GPU and CPU is different. Is there anything I'm doing wrong?

**Comment by meiqua** [comment]
Oh, it's due to tiny differences of float between gpu and cpu. When casting to int, it may have a diff of 1, so totally same assertion is too strong here. This problem tends to come out if we have 100 rand poses.
You can check this by putting these codes before assertion:
``` c++
        for(size_t i=0; i<mat4_v.size(); i++){
            int diff_v = std::accumulate(result_diff.data() + i*height*width,
                                         result_diff.data() + (i+1)*height*width, 0);
            if(diff_v > 0){
                std::cout << "test: " << diff_v << std::endl;

                cv::Mat depth = cv::Mat(height, width, CV_32SC1, result_diff.data() + i*height*width);
                cv::imshow("diff_mask", depth>0);
                cv::waitKey(0);
            }
        }
```

**Comment by Guptajakala** [comment]
@meiqua  
This is the problem. Thank you!
