### ISSUE TITLE
kdtree building does not stop

### ISSUE THREAD

**Issue by joy-yjl** [meiqua/pose_refine#8]
When I use the code to building  kdtree, it enters an endless loop, and there are always new nodes that can be split.

**Comment by meiqua** [comment]
Do your point clouds have many exact same points, for example, many (0, 0, 0)?

**Comment by meiqua** [comment]
I guess it's because those points always go one side, so splitting won't stop. You can refer to [this commit](https://github.com/meiqua/pose_refine/commit/e87e609e3bcccaf9b1343ea66cb21e64576bb659) to test. Now it has same chance to go both side.

**Comment by joy-yjl** [comment]
> I guess it's because those points always go one side, so splitting won't stop. You can refer to [this commit](https://github.com/meiqua/pose_refine/commit/e87e609e3bcccaf9b1343ea66cb21e64576bb659) to test. Now it has same chance to go both side.

thank you for your reply. this new commit fixed this bug. Now it works.
